services:

 nginx:
  images: nginx:vv1
  build:
   context: requirements/nginx
   dockerfile: Dockerfile
  ports:
   - "443:443"
  container_name: nginx
  depends_on:
   - wordpress
  networks:
   - inception_net
  volumes:
   - wordpress_data:/var/www/html
  env_file:
   - .env
  restart: on-failure


 wordpress:
  image: wordpress:vv1
  build:
   context: requirements/wordpress
   dockerfile: Dockerfile
  container_name: wordpress
  networks:
   - inception_net
  depends_on:
   - mariadb
  env_file:
   - .env
  volumes:
   - wordpress_data:/var/www/html
   - adminer_script:/adminer
  restart: on-failure


 mariadb:
  image: mariadb:vv1
  container_name: mariadb
  build:
   context: requirements/mariadb
   dockerfile: Dockerfile
  env_file: .env
  networks:
     - inception_net
  volumes:
     - mariadb_data:/var/lib/mysql   
  restart: on-failure

 redis:
  image: redis:vv1
  container_name: redis
  build:
   context: requirements/bonus/redis
   dockerfile: Dockerfile
  networks:
   - inception_net
  restart: on-failure
  depends_on:
   - wordpress
 
 ftp:
  image: ftp:vv1
  container_name: ftp
  build:
   context: requirements/bonus/ftp
   dockerfile: Dockerfile
  networks:
   - inception_net
  restart: on-failure
  depends_on:
   - wordpress
  volumes:
   - wordpress_data:/var/www/html
  env_file:
   - .env
  ports: 
   - "21:21"
   - "20000-20100:20000-20100"

 me:
  image: me
  container_name: me
  build:
   context: requirements/bonus/me
   dockerfile: Dockerfile
  ports:
   - "80:80"
  restart: on-failure


 adminer:
  image: adminer:vv1
  container_name: adminer
  build:
   context: requirements/bonus/adminer
   dockerfile: Dockerfile
  depends_on:
   - wordpress
  restart: on-failure
  volumes:
   - adminer_script:/adminer
  networks:
   - inception_net
  ports:
   - "5000:5000"

 cadviser:
  image: cadvisor:vv1
  container_name: cadvisor
  build:
   context: requirements/bonus/cadvisor
   dockerfile: Dockerfile
  ports:
   - "7070:8080"
  volumes:
   - /:/rootfs:ro
   - /var/run/docker.sock:/var/run/docker.sock
   - /sys:/sys:ro
   - /var/lib/docker/:/var/lib/docker:ro
  restart: on-failure


networks:
 inception_net:

# volumes:
#  wordpress_data:
#  mariadb_data:


volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/houamrha/data/wordpress
      o: bind

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/houamrha/data/mariadb
      o: bind

  adminer_script:
    driver: local
    driver_opts:
      type: none
      device: /home/houamrha/data/adminer
      o: bind
