services:

 nginx:
  build:
   context: requirements/nginx
   dockerfile: Dockerfile
  ports:
   - "9876:443"
  container_name: nginx
  depends_on:
   - wordpress
  networks:
   - inception_net
  volumes:
   - wordpress_data:/var/www/html
  env_file:
   - .env
  restart: on-failure


 wordpress:
  build:
   context: requirements/wordpress
   dockerfile: Dockerfile
  container_name: wordpress
  networks:
   - inception_net
  depends_on:
   - mariadb
  env_file:
   - .env
  volumes:
   - wordpress_data:/var/www/html
  restart: on-failure

 mariadb:
  container_name: mariadb
  build:
   context: requirements/mariadb
   dockerfile: Dockerfile
  env_file: .env
  networks:
     - inception_net
  volumes:
     - mariadb_data:/var/lib/mysql   
  restart: on-failure

 redis:
  container_name: redis
  build:
   context: requirements/bonus/redis
   dockerfile: Dockerfile
  networks:
   - inception_net
  restart: on-failure


networks:
 inception_net:

volumes:
 wordpress_data:
 mariadb_data:
