services:
 nginx:
  build:
   dockerfile: nginx/Dockerfile
  ports:
   - "9876:80"
  container_name: nginx_c
 wordpress:
  image: wordpress
  build:
   dockerfile: wordpress/Dockerfile
  ports:
   - "8080:80"
  container_name: wordpress_c

services:
  mariadb:
    container_name: md_c
    build:
     context: mariadb
     dockerfile: Dockerfile
    env_file: .env