services:

#  nginx:
#   build:
#    dockerfile: nginx/Dockerfile
#   ports:
#    - "9876:80"
#   container_name: nginx_c

 wordpress:
  build:
   context: requirements/wordpress
   dockerfile: Dockerfile
  ports:
   - "8080:80"
  container_name: wd_c
  networks:
   - wordpress_md_net
  depends_on:
   - mariadb
  env_file:
   - .env
#   restart: on-failure

 mariadb:
  container_name: md_c
  build:
   context: requirements/mariadb
   dockerfile: Dockerfile
  env_file: .env
  networks:
     - wordpress_md_net
  # restart: on-failure

networks:
 wordpress_md_net:
  driver: bridge